### ISSUE TITLE
Mocket can't mock writing compressed data by zlib

### ISSUE THREAD

**Issue by wen-aa** [mindflayer/python-mocket#54] opened 2017-05-26 01:34 UTC
I tried to use Mocket to mock redis and write the compressed data, it threw this error.

```python
In [1]: from mocket import compat

In [2]: import zlib

In [3]: s = '{[]}'

In [4]: compat.decode_from_bytes(zlib.compress(s))
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-4-0af92b1f9211> in <module>()
----> 1 compat.decode_from_bytes(zlib.compress(s))

/usr/local/lib/python2.7/dist-packages/mocket/compat.pyc in decode_from_bytes(s, charset)
     35 def decode_from_bytes(s, charset=encoding):
     36     if isinstance(s, byte_type):
---> 37         s = s.decode(charset)
     38     return text_type(s)
     39

/usr/lib/python2.7/encodings/utf_8.pyc in decode(input, errors)
     14
     15 def decode(input, errors='strict'):
---> 16     return codecs.utf_8_decode(input, errors, True)
     17
     18 class IncrementalEncoder(codecs.IncrementalEncoder):

UnicodeDecodeError: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte
```

**Comment by mindflayer** [comment] 2017-05-26 05:40
In your example the problem is that you are trying to decode something
which is not Unicode, so you would have to specify the right 'encoding'.
But I feel like this is not the real problem you are experiencing.
May you open a pull request adding a test with a small example of what you
want to do?
Or at least comment here with a snippet which fails with this error.

Please note I'll be travelling during the next days, so I can't promise
I'll have time to work on it, but maybe to review your code and trying to
help you and understand if it's a bug or not.

Regards,
Giorgio


Il 26 mag 2017 03:34, "wen-aa" <notifications@github.com> ha scritto:

I tried to use Mocket to mock redis and write the compressed data, it threw
this error.

In [1]: from mocket import compat

In [2]: import zlib

In [3]: s = '{[]}'

In [4]: compat.decode_from_bytes(zlib.compress(s))---------------------------------------------------------------------------UnicodeDecodeError
                       Traceback (most recent call
last)<ipython-input-4-0af92b1f9211> in <module>()----> 1
compat.decode_from_bytes(zlib.compress(s))
/usr/local/lib/python2.7/dist-packages/mocket/compat.pyc in
decode_from_bytes(s, charset)
     35 def decode_from_bytes(s, charset=encoding):
     36     if isinstance(s, byte_type):---> 37         s = s.decode(charset)
     38     return text_type(s)
     39
/usr/lib/python2.7/encodings/utf_8.pyc in decode(input, errors)
     14
     15 def decode(input, errors='strict'):---> 16     return
codecs.utf_8_decode(input, errors, True)
     17
     18 class IncrementalEncoder(codecs.IncrementalEncoder):
UnicodeDecodeError: 'utf8' codec can't decode byte 0x9c in position 1:
invalid start byte

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/mindflayer/python-mocket/issues/54>, or mute the thread

**Comment by mindflayer** [comment] 2017-05-29 06:12
Any step forward, @wen-aa?

**Comment by mindflayer** [comment] 2017-06-03 21:22
I'm going to close this issue. Please reopen it if you feel like there's something more to discuss.

**Closed by mindflayer** 2017-06-03 21:22 UTC
